name: Cherry-pick

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: Which commit to cherry-pick
        required: true
      tags:
        type: string
        description: Which tags to cherry-pick on
        required: true

jobs:
  release-staging:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Test cherry-pick
        run: |
          git --version
          echo "-- Git Version --"
          git fetch
          git status
          echo -e "\n"

          # Cherry picking commit in each tags separated by a comma
          for tag in $(echo "${{ github.event.inputs.tags }}" | tr ',' '\n'); do
            echo -e "\n-- Cherry-picking commit ${{ github.event.inputs.commit }} in tag $tag --"
            echo "Checkout tag $tag"
            git checkout $tag
            echo "Cherry-pick commit ${{ github.event.inputs.commit }} in tag $tag"
            git cherry-pick ${{ github.event.inputs.commit }}

            # Opens a pull request for the cherry pick
            echo "Pushing changes"
            git push origin $tag
            echo "Opening pull request"
            gh pr create --title "Cherry-pick ${{ github.event.inputs.commit }} in tag $tag" --body "Cherry-pick ${{ github.event.inputs.commit }} in tag $tag" --base $tag --head $tag
          done
