name: "Test"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      api:
        description: "API to test"
        default: "Test"
        required: false

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
          - name: Set up package.json path
            id: package-path
            run: |
              if [ ${{ github.ref_name }} ]; then
                path=$(echo "${{ github.ref_name }}")/package.json
              else
                path=$(pwd)/package.json
              fi
    
              echo "Path is $path"
              echo "package_path=$path" >> "$GITHUB_OUTPUT"